### ISSUE TITLE
error importing advertising.csv

### ISSUE THREAD

**Issue by johnnyboi1016** [learn-co-curriculum/dsc-ols-statsmodels-lab#1]
Hello the solution has the command below to import the csv file as a pandas series:

data = pd.read_csv('Advertising.csv', index_col=0)

As shown it throws an error that file is not found; the correct file gets imported when the filename is corrected with a lowercase a

**Comment by hoffm386** [comment]
Thanks for flagging this; we initially tested the lab on a file system that is not case sensitive.

Fixed by https://github.com/learn-co-curriculum/dsc-ols-statsmodels-lab/commit/146434c0e03d422ac703041f6dcc349064d63f41
